=== veeravilla/octbatch/BusinessObjects/bin/xsd/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.test.com/bankapp/employee"
	xmlns:tns="http://www.test.com/bankapp/employee" elementFormDefault="qualified">
	
    <element name="Employee" type="tns:Emp"></element>

    <complexType name="Emp">
    	<sequence>
    		<element name="eno" type="int"></element>
    		<element name="ename" type="string"></element>
    		<element name="salary" type="double"></element>
    		<element name="Address" type="tns:Address"/>
    	</sequence>
    </complexType>
    
    <complexType name="Address">
    		<sequence>
    			<element name="city"  type="string"/>
    			<element name="zipcode"  type="string"/>
    			<element name="state"  type="string"/>
    		</sequence>
    </complexType>
</schema>

=== veeravilla/octbatch/BusinessObjects/bin/xsd/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Employee xmlns:tns="http://www.test.com/bankapp/employee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.test.com/bankapp/employee employee.xsd ">
	<tns:eno>101</tns:eno>
	<tns:ename>Goapl</tns:ename>
	<tns:salary>4500.3</tns:salary>
	<tns:Address>
		<tns:city>Plymouth</tns:city>
		<tns:zipcode>55447</tns:zipcode>
		<tns:state>MI</tns:state>
	</tns:Address>
</tns:Employee>
